### ISSUE TITLE
Add family profile view 

### ISSUE THREAD

**Issue by isabelcshaw** [OpenSRP/opensrp-client-goldsmith#13]
- [x] Show family name, family location (on second row) and family icon. For v1, we do not need to show walking distance. 

- [x] Show the list of all family members. These components include full name, age, and gender. The head of household should always be the first family member in the list and will be indicated below their gender. Clicking on a family member will take the user to their individual profile view. 

- [ ] Show the list of all tasks for that family. When the user clicks on a task, it should open up the relevant form. For v1, this view does not need to show the recently done tasks. If we are tight on time, we can discuss this view more. If absolutely necessary, we could deliver v1 without this view altogether. 

- [x] Include the "add member" button at the bottom of the view that allows the user to add a new family member. 

- [ ] Include an option menu in the top right corner. For v1, the menu have a single option: remove family member. _If we are tight on time, the option menu does not have to be delivered in v1._ 

Mocks: https://marvelapp.com/prototype/b82gf33/screen/72855453
**Members:** 
<img width="340" alt="Screen Shot 2020-10-11 at 7 08 30 PM" src="https://user-images.githubusercontent.com/12836913/95707764-48c75d80-0c0f-11eb-910d-e7995bbefb54.png">

**Tasks:** 
<img width="340" alt="Screen Shot 2020-10-11 at 7 08 14 PM" src="https://user-images.githubusercontent.com/12836913/95708232-955f6880-0c10-11eb-96a1-110e6a38efe6.png">
